CREATE TABLE IF NOT EXISTS crypton_tags(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS crypton_tag_mapping(
    tag_id INTEGER NOT NULL,
    note_id INTEGER NOT NULL,
    FOREIGN KEY (tag_id) REFERENCES crypton_tags(id)
	ON DELETE CASCADE,
    FOREIGN KEY (note_id) REFERENCES crypton_notes(id)
	ON DELETE CASCADE
);